#!/bin/sh

set -e

PREREQ="cryptroot"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/ykchalresp
copy_exec /usr/bin/ykinfo
copy_exec /usr/bin/sha256sum
cp /usr/share/yubikey-luks/ykluks-keyscript "${DESTDIR}/sbin/ykluks-keyscript"
cp /etc/ykluks.cfg "${DESTDIR}/etc/ykluks.cfg"
cp -pnL /usr/lib/yubikey-luks/initramfs-suspend "${DESTDIR}/suspend"
chmod 755 "${DESTDIR}/suspend"

exit 0
