#! /bin/sh

set -e

PREREQ=""


message()
{
    if [ -x /bin/plymouth ] && plymouth --ping; then
        plymouth message --text="$*"
    else
        echo "$@" >&2
    fi
    return 0
}

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

#if [ -e /etc/yubikey-challenge ]; then
#	message "Creating a new Yubikey challenge!"
#	R="$(ykchalresp -2 "$(cat /etc/yubikey-challenge)")"
#	echo -n "$R" > /etc/old_key
#	uuidgen > /etc/yubikey-challenge
#	R="$(ykchalresp -2 "$(cat /etc/yubikey-challenge)")"
#	echo -n "$R" > /etc/new_key
#	cryptsetup  --key-file=/etc/old_key luksChangeKey /dev/sda5 /etc/new_key
#	rm -f /etc/old_key /etc/new_key
	message "Welcome!"
#fi
exit 0
